### ISSUE TITLE
erro when patching

### ISSUE THREAD

**Issue by ahmedmz877** [rebrowser/rebrowser-patches#1]
FATAL ERROR: Package name is "puppeteer-real-browser", but we're looking for "puppeteer-core". Check your package path
 i am using https://github.com/zfcsoftware/puppeteer-real-browser/ 
 how can i use the patch with it please

**Comment by nwebson** [comment]
How do you call the patcher? This package has `puppeteer` as a dependency, so you should use different `packagePath` when you run the script. You need to find where is `puppeteer` folder inside your project.

**Comment by ahmedmz877** [comment]
npx rebrowser-patches patch --packagePath ./node_modules/puppeteer-real-browser

**Comment by nwebson** [comment]
So, after you run `npm i puppeteer-real-browser`, it will install all deps, so your actual puppeteer code will be in `./node_modules/puppeteer-core`, you can use this path for the patcher.

**Comment by thiyagarajanp98** [comment]
I actually used this `npx rebrowser-patches patch --packagePath /YT_uploader/node_modules/puppeteer-core` and receiving below error.

![image](https://github.com/user-attachments/assets/9511d6c5-8867-4df8-9fb2-5d7b83ad225d)

**Comment by nwebson** [comment]
@thiyagarajanp98 - this means you don't have `patch` command installed. You need to install it in your OS, or inside the docker container.

**Comment by ahmedmz877** [comment]
> I actually used this command `npx rebrowser-patches patch --packagePath /YT_uploader/node_modules/puppeteer-core` and receiving below error.
> 
> ![image](https://private-user-images.githubusercontent.com/60639114/355958513-9511d6c5-8867-4df8-9fb2-5d7b83ad225d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMwOTEyMTYsIm5iZiI6MTcyMzA5MDkxNiwicGF0aCI6Ii82MDYzOTExNC8zNTU5NTg1MTMtOTUxMWQ2YzUtODg2Ny00ZGY4LTlmYjItNWQ3YjgzYWQyMjVkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA4VDA0MjE1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY0ZTFlODg0ZmQ3NzJlMWMxMjI1YTM4NzQzOGIyOGU4ZDcxZTc4ZmU4MDk5NWYzMjRhMzQxOWM0Y2EyNmVkY2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.80LGvL1srnn_0s_hjJ0uvT_J0Zdorohy0WZZWJRgV7w)

Use https://git-scm.com/downloads to install the patch

**Comment by thiyagarajanp98** [comment]
still not working

![image](https://github.com/user-attachments/assets/9e8f6ced-a00b-4518-a798-0f487fbffbbf)

**Comment by ahmedmz877** [comment]
> still not working
> 
> ![image](https://private-user-images.githubusercontent.com/60639114/356186167-9e8f6ced-a00b-4518-a798-0f487fbffbbf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMxMzMwNDgsIm5iZiI6MTcyMzEzMjc0OCwicGF0aCI6Ii82MDYzOTExNC8zNTYxODYxNjctOWU4ZjZjZWQtYTAwYi00NTE4LWE3OTgtMGY0ODdmYmZmYmJmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA4VDE1NTkwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk3YWQzYThmYWFkODc5ZmEwZDI2YzdhNjM1N2FkNzI0MWI0NzAyYmNkOWVjODg4Zjg1ZjhiNDBhZjFlMTQzMzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.DI0GgDFY9sbSOLT5iu8eeOBnK3Kj8P3TjaOi0cX-l3g)

use this 
in YT_uploader run
npx rebrowser-patches patch --packagePath ./node_modules/puppeteer-core
