### ISSUE TITLE
Good job bro, when Playwright?

### ISSUE THREAD

**Issue by ChrisYP** [rebrowser/rebrowser-patches#10]
Good job bro, when Playwright?

**Comment by nwebson** [comment]
Thanks, it's work in progress. Maybe in a week or two if I see enough demand from community.

**Comment by asim-shrestha** [comment]
Would love some functionality for playwright @nwebson!

**Comment by polatdev** [comment]
@nwebson we are waiting dudee :)

**Comment by thucvu97** [comment]
@polatdev Me too

**Comment by Taoli96** [comment]
Me too !!!

**Comment by Dmtreaqq** [comment]
Would be awesome if we will receive it for playwright ! 😄 👍

**Comment by issue-reporter** [comment]
+1 for playwright support.

**Comment by halvaenjoyer** [comment]
me here not being a silent awaiter of playwright support :)

**Comment by nwebson** [comment]
Hey there! Finally released patches for Playwright. For now, it's for JS version only. Python version is coming soon.

You can patch it manually or use drop-in replacements: [rebrowser-playwright](https://www.npmjs.com/package/rebrowser-playwright) and [rebrowser-playwright-core](https://www.npmjs.com/package/rebrowser-playwright-core)

Please let me know if anything is broken after the patch. Thanks 🙏

**Comment by regseb** [comment]
I tested `rebrowser-playwright` with _rebrowser-bot-detector_ using:

- `package.json`

  ```json
  {
    "name": "testcase",
    "version": "1.0.0",
    "type": "module",
    "dependencies": {
      "rebrowser-playwright": "1.47.2"
    }
  }
  ```

- `index.js`

  ```javascript
  import fs from "node:fs/promises";
  import { chromium } from "rebrowser-playwright";

  process.env.REBROWSER_PATCHES_DEBUG = 1;

  const browser = await chromium.launch();
  const context = await browser.newContext();
  const page = await context.newPage();

  await page.goto("https://rebrowser.github.io/rebrowser-bot-detector/");

  // dummyFn
  await page.evaluate(() => window.dummyFn())
  // sourceUrlLeak
  await page.evaluate(() => document.getElementById('detections-json'))
  // mainWorldExecution
  await page.evaluate(() => document.getElementsByClassName('div'))

  await page.screenshot({ path: "./results.png", fullPage: true });
  await fs.writeFile("./results.html", await page.content());

  await context.close();
  await browser.close();
  ```

When I run `node index.js`, I get the following error:

```
node:internal/modules/run_main:115
    triggerUncaughtException(
    ^

page.evaluate: TypeError: window.dummyFn is not a function
    at eval (eval at evaluate (:234:30), <anonymous>:1:14)
    at UtilityScript.evaluate (<anonymous>:236:17)
    at UtilityScript.<anonymous> (<anonymous>:1:44)
    at /home/regseb/dev/tc/rebrowser/index.js:13:12

Node.js v22.4.1
```

Did I miss something?

**Comment by nwebson** [comment]
@regseb patch worked fine, you need to read this post: https://rebrowser.net/blog/how-to-access-main-context-objects-from-isolated-context-in-puppeteer-and-playwright-23741
