### ISSUE TITLE
puppeteer-extra support

### ISSUE THREAD

**Issue by Astralights366** [rebrowser/rebrowser-patches#12]
Thank you a lot for the patch, it's working with puppeteer-core. I couldn't make it work with puppeteer-extra however, because puppeteer-extra is choosing "puppeteer" first over "puppeteer-core" ([puppeteer-extra/src/index.ts](https://github.com/berstend/puppeteer-extra/blob/master/packages/puppeteer-extra/src/index.ts)) Here is my quick patch fixing the issue.

**patches/puppeteer-extra+3.3.6.patch**

```
diff --git a/node_modules/puppeteer-extra/dist/index.cjs.js b/node_modules/puppeteer-extra/dist/index.cjs.js
index 2596430..242cf24 100644
--- a/node_modules/puppeteer-extra/dist/index.cjs.js
+++ b/node_modules/puppeteer-extra/dist/index.cjs.js
@@ -447,17 +447,18 @@ const addExtra = (puppeteer) => new PuppeteerExtra(puppeteer);
  */
 function requireVanillaPuppeteer() {
     try {
-        return [require('puppeteer'), undefined];
+        return [require('puppeteer-core'), undefined];
     }
     catch (_) {
-        // noop
+        //noop
     }
     try {
-        return [require('puppeteer-core'), undefined];
+        return [require('puppeteer'), undefined];
     }
     catch (err) {
         return [undefined, err];
     }
+    
 }
 
 exports.PuppeteerExtra = PuppeteerExtra;
```

**Comment by nwebson** [comment]
Thanks for sharing this. I'm curious what version of pptr is used when you use it with pptr-extra? Seems like package wasn't updated for a long time, so I'm not even sure that my patch is compatible with that version.

**Comment by ottodriver** [comment]
It's compatible, but it needs to be used with "addExtra", check puppeteer-extra docs.

**Comment by Dmtreaqq** [comment]
@Astralights366 did you make it work with puppeter-extra ?

**Comment by Astralights366** [comment]
@Dmtreaqq yes, by applying the patch in my original post, or as ottodriver mentioned it may be possible with "addExtra" (i didn't test), however I had issues with page.evaluate and others while using this project, so I opted for something else for now with my use-case.

**Comment by nwebson** [comment]
@Astralights366 could you please share some details about the issues? I would try to address it and find some solution.

**Comment by Biogasbottle** [comment]
import puppeteer, { Browser, Page } from 'rebrowser-puppeteer';

import { addExtra } from 'puppeteer-extra';
import StealthPlugin from 'puppeteer-extra-plugin-stealth';

const stealth = StealthPlugin();
const pextra = addExtra(puppeteer);

for (const item of [stealth])
{
    pextra.use(item);
}

process.env.REBROWSER_PATCHES_RUNTIME_FIX_MODE = "alwaysIsolated"

pextra.
    launch({
        headless: false, defaultViewport: null, protocolTimeout: 0,
        args: ['--start-maximized',
            '--disable-features=Translate,OptimizationHints,MediaRouter,DialMediaRouteProvider,CalculateNativeWinOcclusion,InterestFeedContentSuggestions,CertificateTransparencyComponentUpdater,AutofillServerCommunication,PrivacySandboxSettings4,AutomationControlled'
            ]
    })
    .then(async (browser: Browser) =>
    {
        const page = await browser.newPage();
      
         await page.goto('https://bot-detector.rebrowser.net')
       
        await Promise.all([
            page.click(".button"),
            page.waitForNavigation({ waitUntil: 'domcontentloaded' })
        ]);
-------------------------------------------------------
Tested ok.

but, for some SPA page, waitForSelector always timeout after a navigation by button Click or 'Enter' type. I turn to [puppeteer-real-browser](https://github.com/zfcsoftware/puppeteer-real-browser),  still timed out. And I also need to read a window variables, and tried ways introduced here and puppeteer-real-browser there, none works.  struggling...

**Comment by nwebson** [comment]
@Biogasbottle please create a new issue with that waitForSelector bug and don't forget to include your code for reproducing.
