### ISSUE TITLE
Update flow

### ISSUE THREAD

**Issue by AndriusCTR** [rebrowser/rebrowser-patches#14]
So what is the update process after installation when new package version is released?

Just npm install rebrowser-patches on top of existing installation and that's it? Or need to apply patch command after each package version update?

**Comment by nwebson** [comment]
There is no specific flow for update the patch (at least yet).
I would suggest remove package folder or whole node_modules folder, run npm/yarn install, and then apply the patches with the latest version.

**Comment by AndriusCTR** [comment]
> There is no specific flow for update the patch (at least yet). I would suggest remove package folder or whole node_modules folder, run npm/yarn install, and then apply the patches with the latest version.

Remove the whole node_modules folder? No thanks.. I have other packages there that are important. Need to have solution for this. How about uninstall puppeteer-core and reinstall?

**Comment by nwebson** [comment]
> > There is no specific flow for update the patch (at least yet). I would suggest remove package folder or whole node_modules folder, run npm/yarn install, and then apply the patches with the latest version.
> 
> Remove the whole node_modules folder? No thanks.. I have other packages there that are important. Need to have solution for this. How about uninstall puppeteer-core only and reinstall it and then apply patch? Will that work?

Yes, that should totally work. The idea is to remove `node_modules/puppeteer-core`, then it's safe to re-apply the patch.
