### ISSUE TITLE
PATCH IS NOT RECOGNISED AS AN INTERNAL OR EXTERNAL COMMAND 

### ISSUE THREAD

**Issue by Uncletee1996** [rebrowser/rebrowser-patches#16]
![17250266115555885697112617650339](https://github.com/user-attachments/assets/ba707e8b-2333-4464-9e7b-5451f37f3016)
Hey am having this error, when am trying to install patch on my computer 

What could be the issue

**Comment by nwebson** [comment]
I was able to test the patcher on a Windows machine, so I added some tips to the readme about it:
https://github.com/rebrowser/rebrowser-patches?tab=readme-ov-file#patch-command-on-windows
