### ISSUE TITLE
Playwright Support?

### ISSUE THREAD

**Issue by issue-reporter** [rebrowser/rebrowser-patches#19]
Here to add my voice to the pile for playwright support. We all would greatly appreciate it.

**Comment by nwebson** [comment]
Thanks. Work in progress.

**Comment by RoyHP** [comment]
@nwebson Do you know if it's technically possible to write the CDP patch into https://www.npmjs.com/package/puppeteer-extra-plugin-stealth? (since it can work in playwright via playwright-extra) Or does puppeteer's source code need to be modified like you're doing now?

I understand that might be a conflict of interest for you, but was curious if it's technically possible.

**Comment by nwebson** [comment]
@RoyHP unfortunately, it's not possible to fix it via some JS above pptr/playwright level. It's quite core feature (Runtime.enable) and these libraries cannot live without it unless being patched right in the heart.

P.S. Playwright support almost finished, doing some final tests. Hopefully, will be able to release it this week.

**Comment by nwebson** [comment]
Hey there! Finally released patches for Playwright. For now, it's for JS version only. Python version is coming soon.

You can patch it manually or use drop-in replacements: [rebrowser-playwright](https://www.npmjs.com/package/rebrowser-playwright) and [rebrowser-playwright-core](https://www.npmjs.com/package/rebrowser-playwright-core)

Please let me know if anything is broken after the patch. Thanks 🙏

**Comment by iSuslov** [comment]
hey @nwebson, it seems like after patching we get only one issue fixed (runtimeEnableLeak) according to bot detector:

<img width="1394" alt="Screenshot 2024-09-28 at 9 45 01 PM" src="https://github.com/user-attachments/assets/2c2a2cec-4677-457e-b6c7-e9f147c77705">

I'm running through VSCode test runner, maybe that's the issue

**Comment by nwebson** [comment]
@iSuslov it looks all good, you need to follow the tips it shows in the each detection, it's all done with settings, not with the patch.

**Comment by tonybruess** [comment]
I'm testing the playwright patches and I can't seem to call `.click()`. Is this expected?

I'm also getting the following errors in the logs. Will try to create a minimal reproducible testcase:

```
[rebrowser-patches][frames._context] cannot create utility world
[rebrowser-patches][frames._context] cannot create utility world
[rebrowser-patches][frames._context] cannot create utility world
[rebrowser-patches][frames._context] cannot create utility world
[rebrowser-patches][frames._context] cannot create utility world
[rebrowser-patches][frames._context] cannot create utility world
```

**Comment by tonybruess** [comment]
Here's a simple reproducible test case:

```
import { chromium } from "playwright-core";

const browser = await chromium.launch({
  headless: false
})
const context = await browser.newContext({})
const page = await context.newPage()

await page.goto('https://example.com')
await page.click('a')
```

**Comment by nwebson** [comment]
@tonybruess thanks for the detailed bug report. I just published a new version of `rebrowser-playwright-core` and also updated this repo. 
Please try again with the latest version.

**Comment by tonybruess** [comment]
The latest version fixes playwright support for me!
