### ISSUE TITLE
Error: "context is not defined" when trying to access tripple nested Iframe.

### ISSUE THREAD

**Issue by VJO-JavaScript** [rebrowser/rebrowser-patches#20]
### Let me start by saying this patch is dope.

Here is the error I'm currently trying to fix. It's for a tripple nested Iframe... which is pretty horrible in itself lol.

**Website:** live.signup.com (Microsofts signup page, specifically the section with the Funcaptcha)

Ran with "alwaysIsolated"

**Code that triggers the error:**     
 ```
const outerFrameElement = await listenForFirstXpath(page, xpaths.outer_frame);
    const outerFrame = await outerFrameElement.contentFrame();

    await randomTimeout();

    // Middle Frame
    const middleFrameElement = await listenForFirstXpath(outerFrame, xpaths.middle_frame)
    const middleFrame = await middleFrameElement.contentFrame();
    await randomTimeout();
    // await new Promise(resolve => setTimeout(resolve, 2147483647))
   

    // await new Promise(resolve => setTimeout(resolve, 2147483647))
    const innerFrameElement = await listenForFirstXpath(middleFrame, xpaths.inner_frame);
    const innerFrame = await innerFrameElement.contentFrame()
    await randomTimeout()

    const visualCaptchaNextButton = await listenForFirstXpath(innerFrame, xpaths.visual_captcha_next_button)
    visualCaptchaNextButton.click()
}

async function listenForFirstXpath(page, xpaths, waitTime = 30000) {
    if (!Array.isArray(xpaths)) throw new Error('xpaths must be an array')
    const listeners = []
    for (const xpath of xpaths) {
        const listener = page.waitForSelector(`xpath/${xpath}`, { timeout : waitTime })
        listeners.push(listener)
    }       
    const firstResolved = await Promise.race(listeners)

    // if (!firstResolved) throw new Error(`No visible elements found for xpaths ${xpaths.join(', ')} within ${waitTime}ms`)

    return firstResolved
}
```

**The complete error logs:**
[rebrowser-patches][acquireContextId] id = -1, name = undefined, fixMode = alwaysIsolated
content: 
[rebrowser-patches][FrameManager] initialize
[rebrowser-patches] onFrameNavigated, navigationType = Navigation, id = 2CA6DFACDA2D4295F04F3F6375AD5D3B, url = :
[rebrowser-patches] onFrameNavigated, navigationType = Navigation, id = 2CA6DFACDA2D4295F04F3F6375AD5D3B, url = https://iframe.arkoselabs.com/B7D8911C-5CC8-A9A3-35B0-554ACEE604DA/index.html?mkt=en&data=Rc69+CQhwobIv7nT.wuJDoj235+nxy42Ac+6LEquic/z46y4Lc3LvJqvgLdiTPAG1tGjcJEt2KEgDv37+BOy/YaxUBsVwaE5L1T+LdjE9uH/hDq0gmAnmRJ2yfZIQSE1/9G9TZ+YMTLVU71ReVrUbJjLG916A4qaOfsQrwBiiRfM=
[rebrowser-patches] onFrameNavigated, navigationType = Navigation, id = 809BA3D317B79F06146CF7F66D29E204, url = https://client-api.arkoselabs.com/v2/2.9.0/enforcement.b3b1c9343f2ef3887d61d74272d6a3af.html
[rebrowser-patches][acquireContextId] id = -1, name = undefined, fixMode = alwaysIsolated
[rebrowser-patches] onFrameNavigated, navigationType = Navigation, id = DBEEC326672D3D63B346E61421A5005A, url = https://client-api.arkoselabs.com/fc/assets/ec-game-core/game-core/1.23.2/standard/index.html?session=28017f5a60559b882.7612606205&r=eu-west-1&meta=7&meta_height=325&metabgclr=%23ffffff&metaiconclr=%23757575&mainbgclr=%23ffffff&maintxtclr=%231B1B1B&guitextcolor=%23747474&lang=en&pk=B7D8911C-5CC8-A9A3-35B0-554ACEE604DA&at=40&ag=101&cdn_url=https%3A%2F%2Fclient-api.arkoselabs.com%2Fcdn%2Ffc&lurl=https%3A%2F%2Faudio-eu-west-1.arkoselabs.com&surl=https%3A%2F%2Fclient-api.arkoselabs.com&smurl=https%3A%2F%2Fclient-api.arkoselabs.com%2Fcdn%2Ffc%2Fassets%2Fstyle-manager&theme=default

ReferenceError: context is not defined
    at registerOutlookAccount (/home/kali/Downloads/outlookAccountGenerator/automationScripts/outlookSignup.js:147:29)
    
    
**HTML Code that causes error attached**
[errrorHtmlRebrowser.txt](https://github.com/user-attachments/files/17009552/errrorHtmlRebrowser.txt)

**Comment by nwebson** [comment]
I love the bug report, looks very detailed, thank you.

```
ReferenceError: context is not defined
at registerOutlookAccount (/home/kali/Downloads/outlookAccountGenerator/automationScripts/outlookSignup.js:147:29)
```
It looks like the error itself is in one of your files, it's outside puppeteer. Could you share what's going on there?
