### ISSUE TITLE
Why web workers are not supported?

### ISSUE THREAD

**Issue by Logesh08** [rebrowser/rebrowser-patches#23]
```
if (this.#id === -3) {
       throw new Error('[rebrowser-patches] web workers are not supported in alwaysIsolated mode');
}
```

**Comment by nwebson** [comment]
It's not supported by Chrome as far as I understand as a worker is already isolated from the main page.
Could you please provide specific use case when you need it?

**Comment by Logesh08** [comment]
My question is will puppeteer's Worker.evaluate() methods will work as usual?

Thanks!

**Comment by nwebson** [comment]
Good question, I will appreciate if you could make some code example so I can just run and debug it locally.
Thanks.

**Comment by Logesh08** [comment]
```
page.on('workercreated', async worker => {
      console.log('Worker created: ' + worker.url());
      let title = await worker.evaluate('return document.title');
      console.log(`Title is: ${title}`)
});
```

This one gets error which you defined:

```
/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/ExecutionContext.js:338
            throw new Error('[rebrowser-patches] web workers are not supported in alwaysIsolated mode');
```

**Comment by Logesh08** [comment]
It is working without rebrowser-patches, output:

```
Worker created: blob:https://xyz.com/7418b4f0-8c7e-4790-accf-bf5ccfcdee0a
Name is: <name> 
```

**Comment by nwebson** [comment]
Thanks, I will take a look.

**Comment by Logesh08** [comment]
I would also like to contribute, I'm currently checking that if there is any way to acquire `executionContextId` of web workers, if we have that the problem is solved right. So if you can point me where to do the research I can do that. Currently I'm checking in `https://chromedevtools.github.io/devtools-protocol/`

**Comment by nwebson** [comment]
Web workers are not supported in alwaysIsolated mode because when you try to create an isolated context inside a worker, it throws:
```
ProtocolError: Protocol error (Page.createIsolatedWorld): 'Page.createIsolatedWorld' wasn't found
```

BUT!
📣 I just released a new version of `rebrowser-patches` with a completely new fix for Runtime.Enable leak. 
This fix doesn't lose access to main context and also works in workers 🎉 
It's a complete drop-in replacement, so you don't need to change any of your existing code.
Please try your code with new version.

**Comment by Logesh08** [comment]
Wow that's cool. I'll try it and let you know!!
