### ISSUE TITLE
playwright python import

### ISSUE THREAD

**Issue by danofun** [rebrowser/rebrowser-patches#26]
Thank you for taking the time to develop this excellent piece of software!

Trying to test and I'm not seeing how to call the patch
For example, undetected_playwright uses:
`from undetected_playwright.sync_api import sync_playwright`

The example on your project shows:
`from playwright.sync_api import sync_playwright` 
but after installing rebrowser-playwright, the unpatched playwright appears to be unaffected by this package. Testing on MacOS

**Comment by nwebson** [comment]
The package name is `rebrowser_playwright`, so try to use
`from rebrowser_playwright.sync_api import sync_playwright`

**Comment by danofun** [comment]
> The package name is `rebrowser_playwright`, so try to use `from rebrowser_playwright.sync_api import sync_playwright`

Appreciate the reply. I was trying `from rebrowser-playwright.sync_api import sync_playwright`
Your solution worked. Thank you.

**Comment by nwebson** [comment]
Thanks for reporting, I'm glad 🙏
