### ISSUE TITLE
What am I missing? 

### ISSUE THREAD

**Issue by goodbotboy** [rebrowser/rebrowser-patches#27]
I'm using playwrite python. I thought that the patch was supposed to fix the runtime leak. Rebrowser bot detector says it was detected after I installed it.

**Comment by goodbotboy** [comment]
import re
from rebrowser_playwright.sync_api import Page, expect

def test_headful_bot_detect(page: Page):
    page.goto("https://bot-detector.rebrowser.net/")

    while(True):
        pass

Just modified one of the examples to open a headful browser.

**Comment by bruunand** [comment]
I have the same issue using Playwright, and I'm not sure if I'm missing anything here.

Here's the code to reproduce, running 1.47.100:
```
import { chromium } from "playwright";

// I've tried exporting these env. vars as well
process.env.REBROWSER_PATCHES_RUNTIME_FIX_MODE = "alwaysIsolated";
process.env.REBROWSER_PATCHES_DEBUG = "1";

(async () => {
  const browser = await chromium.launch({
    headless: false,
    args: ["--disable-blink-features=AutomationControlled"],
  });

  const context = await browser.newContext({
    viewport: null,
  });

  const page = await context.newPage();
  await page.goto("https://bot-detector.rebrowser.net/");
  await page.waitForTimeout(1000);
  await page.screenshot({
    path: "leak.png",
  });
  await browser.close();
})();
```

Here's the output:
![leak](https://github.com/user-attachments/assets/c073b874-a20e-40d1-9865-a5688a52cb18)

Other than that, the project seems very promising and eliminates a lot of tedious code.

**Comment by ofirk** [comment]
Hi,
I'm trying to use the patch as well with simple script in python, I'm getting same issue and I can see another issue in the console that the script refused to run, any help will be appreciated!
![example-chromium](https://github.com/user-attachments/assets/e16ab5df-4a47-4b68-8ae9-143e15336305)
![console](https://github.com/user-attachments/assets/95e6f560-512a-4761-b589-ec71d2447989)

**Comment by nwebson** [comment]
@ofirk everything looks fine, click on "How to properly run the tests?" and use this code in your automation script.

**Comment by ofirk** [comment]
> @ofirk everything looks fine, click on "How to properly run the tests?" and use this code in your automation script.

Got it, just missed it. Thanks a lot for a great and awesome repository!
