### ISSUE TITLE
Patching Python Playwright

### ISSUE THREAD

**Issue by cvhoang** [rebrowser/rebrowser-patches#29]
I can't seem to find instructions on how to patch Python Playwright. Did I miss something? Thanks.

**Comment by KrAsH-CoD3** [comment]
> I can't seem to find instructions on how to patch Python Playwright. Did I miss something? Thanks.

At the moment there are no documentation to use it. See this to use it.
https://github.com/rebrowser/rebrowser-patches/issues/26#issuecomment-2390555976

**Comment by nwebson** [comment]
You can either use already patched package [rebrowser-playwright](https://pypi.org/project/rebrowser-playwright/) or just patch/replace js version which you can find in `driver` folder inside python package.
