### ISSUE TITLE
Patched the pup but still getting the CDP detected

### ISSUE THREAD

**Issue by luluhoc** [rebrowser/rebrowser-patches#3]
Patched the pup but still getting the CDP detected

I have installed all and the patch was successful.
```
const puppeteer = _puppeteer.default

const pluginStealth = puppeteerExtraPluginStealth()
pluginStealth.enabledEvasions.delete('user-agent-override') // Remove this specific stealth plugin from the default set
puppeteer.use(pluginStealth)
const pluginUserAgentOverride: PuppeteerExtraPlugin = puppeteerExtraPluginUserAgentOverride({
  userAgent:
    'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36',
  locale: 'en,fr-FR;q=0.9,fr;q=0.8,en-US;q=0.7,pl;q=0.6',
  platform: '"macOS"',
})

const script = fs.readFileSync('./scripts/search.js', {
  encoding: 'utf8',
})

export const redis = new Redis(redisLink)

puppeteer.use(pluginUserAgentOverride)

const firstInit = async () => {
  const browser = await puppeteer.launch({
    headless: false,
    devtools: false,
    userDataDir: './data/bot_data',
    args: minimal_args,
  })
  // const pages = await browser.pages()

  const page = await browser.newPage()

  // await page.evaluateOnNewDocument(() => {
  //   Object.defineProperty(navigator, 'language', {
  //     get: function () {
  //       return 'en-US'
  //     },
  //   })
  //   Object.defineProperty(navigator, 'languages', {
  //     get: function () {
  //       return ['en', 'fr-FR', 'fr', 'en-US', 'pl']
  //     },
  //   })
  // })

  // await page.setCacheEnabled(false)

  // await page.setRequestInterception(true)

  return { page, browser }
}


const test = async () => {
  const { page, browser } = await firstInit()
  await page.goto('https://kaliiiiiiiiii.github.io/brotector/', {
    waitUntil: 'networkidle0',
  })
}

test()
```

Getting this detected on https://kaliiiiiiiiii.github.io/brotector/
```{ "stackLookupCount": 1, "nameLookupCount": 3 }```

```"puppeteer": "^23.0.2",```

<img width="250" alt="image" src="https://github.com/user-attachments/assets/25e6af24-e9ed-4718-9d78-36b6a21b9d20">

**Comment by kaliiiiiiiiii** [comment]
The `Runtime.enable|disable` reconnect thingy is probably not enough fast - good. 

Not even mentioning that the current interval (50ms) could be probably be lowered.

https://github.com/kaliiiiiiiiii/brotector/blob/03cb70133682e3c07edba2e6b7bf700a2f476bef/brotector.js#L73

**Comment by nwebson** [comment]
@luluhoc have you enabled the patch by settings env variable REBROWSER_PATCHES_RUNTIME_FIX_MODE? What mode are you using?

**Comment by luluhoc** [comment]
@nwebson 

I'm using REBROWSER_PATCHES_RUNTIME_FIX_MODE=alwaysIsolated

I have tried it for leboncoin.fr which is datadome and I'm getting blocked still... 

I'm using it with pup stealth as in the code

I have added it at the beginning of the code.

```
process.env.REBROWSER_PATCHES_RUNTIME_FIX_MODE = 'alwaysIsolated'
process.env.REBROWSER_PATCHES_DEBUG = '1'

const prisma = new PrismaClient()

const puppeteer = _puppeteer.default // see https://github.com/motdotla/dotenv#how-do-i-use-dotenv-with-import

const pluginStealth = puppeteerExtraPluginStealth()
pluginStealth.enabledEvasions.delete('user-agent-override') // Remove this specific stealth plugin from the default set
puppeteer.use(pluginStealth)
```

**Comment by nwebson** [comment]
I see you have enabled `REBROWSER_PATCHES_DEBUG`, it's good. Can you see debug messages from `rebrowser-patches` during the execution? If not, then you patched some wrong package which isn't actually used in your code. How do you import `puppeteer` package itself?

**Comment by nwebson** [comment]
@luluhoc do you have any updates?

**Comment by nwebson** [comment]
@luluhoc I think it didn't work for you because you were using cjs, it's fixed now. 
Please read here: https://github.com/rebrowser/rebrowser-patches/issues/6#issuecomment-2305585145
