### ISSUE TITLE
Patch Not Working Puppeter Core

### ISSUE THREAD

**Issue by myaltan** [rebrowser/rebrowser-patches#31]
![image](https://github.com/user-attachments/assets/8dee54db-ba29-469f-88bb-9fa970f830d0)
No matter what I do, it doesn't work. need help

**Comment by myaltan** [comment]
![image](https://github.com/user-attachments/assets/c620febc-e997-4bb6-8249-bb8369daaf88)

**Comment by nwebson** [comment]
Very interesting... Try to install some other version of puppeteer-core, maybe that's the reason. Or just remove node_modules/puppeteer-core folder and run npm install again.

**Comment by myaltan** [comment]
![image](https://github.com/user-attachments/assets/002ff444-23ea-4de2-b056-2acfffa160c5)

**Comment by nwebson** [comment]
Version 22.12.0 is not supported.

You can just use already patched version, package name is [rebrowser-puppeteer-core](https://www.npmjs.com/package/rebrowser-puppeteer-core?activeTab=readme)
