### ISSUE TITLE
[Python] Request for musllinux-compatible build for rebrowser-playwright 

### ISSUE THREAD

**Issue by felipehertzer** [rebrowser/rebrowser-patches#32]
Hello,  

I am attempting to install the Python package on an Alpine Linux environment. However, I encountered an issue with the installation, as shown in the logs below.  

Would it be possible to provide a musllinux-compatible build for `rebrowser-playwright`? This would greatly assist in ensuring compatibility with Alpine Linux.  

Thank you for your attention to this matter.  

**Error Log:**  
```
3.380 Collecting curl_cffi (from -r requirements.txt (line 12))
3.410   Downloading curl_cffi-0.7.3-cp38-abi3-musllinux_1_1_x86_64.whl.metadata (12 kB)
3.450 ERROR: Could not find a version that satisfies the requirement rebrowser-playwright (from versions: none)
3.648 ERROR: No matching distribution found for rebrowser-playwright
```

**Comment by nwebson** [comment]
Hmmm... does it work fine with vanilla `playwright` python package?
I didn't change anything related to platforms and it should support all the same as the original one, but I'm not super handy with python tooling, to be honest.

**Comment by felipehertzer** [comment]
Sorry, it looks like it is not supported https://github.com/microsoft/playwright-python/issues/2207
