### ISSUE TITLE
Didnt pass fingerprint bot detection

### ISSUE THREAD

**Issue by hlamhuy** [rebrowser/rebrowser-patches#33]
![image](https://github.com/user-attachments/assets/0efd1a52-b5c2-4e9f-9225-582be0b818de)
![image](https://github.com/user-attachments/assets/d20c66b6-021b-4917-b61f-81abf5573539)

Playwright version: 1.47.2
I tested various bot detection sites and fingerprint is the only site that failed.

**Comment by nwebson** [comment]
What kind of browser are you using? Is it Chrome for Testing or is it vanilla Chrome?

**Comment by hlamhuy** [comment]
I removed `channel: 'chrome'` and now it passes fingerprint detection. thanks for pointing it out
