### ISSUE TITLE
page.waitForSelector timeout 

### ISSUE THREAD

**Issue by Biogasbottle** [rebrowser/rebrowser-patches#38]
For privacy reasons, I cannot post the code. But I have found how to reproduce it. When the page completes the navigation ‘load’, the page has not been fully rendered by js. At this time, calling waitForSelector to wait for an element to be rendered will time out, even if the element has been rendered before the timeout.

**Comment by halvaenjoyer** [comment]
How come is this a patch issue?

**Comment by nwebson** [comment]
Do you use it with the latest patch version using `addBinding` method?

**Comment by Biogasbottle** [comment]
definitely..

PS D:\************> npm i --save-dev puppeteer puppeteer-core
Debugger listening on ws://127.0.0.1:10061/da63e08e-be17-42d8-ace8-3794139d5d51
For help, see: https://nodejs.org/en/docs/inspector
Debugger attached.

added 2 packages, and audited 549 packages in 1s

150 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
Waiting for the debugger to disconnect...
PS D:\**********> npx rebrowser-patches@latest patch --packageName puppeteer-core
Debugger listening on ws://127.0.0.1:10070/2f00998d-31f9-482b-ad07-c7e375ea9f96
For help, see: https://nodejs.org/en/docs/inspector
Debugger attached.
Need to install the following packages:
rebrowser-patches@1.0.13
Ok to proceed? (y) y

Debugger listening on ws://127.0.0.1:10083/addf472d-35d4-4a55-9b2e-4d32c6086e4f
For help, see: https://nodejs.org/en/docs/inspector
Debugger attached.
Config:
command = patch, packageName = puppeteer-core
packagePath = D:\***********/node_modules/puppeteer-core
------
Found package "puppeteer-core", version 23.6.0
Current patch status = 🟧 unpatched
Result: 🟢 success
Waiting for the debugger to disconnect...
Waiting for the debugger to disconnect...

**Comment by nwebson** [comment]
Please share some code showing this issue so I can debug it locally.
