### ISSUE TITLE
Patch failed

### ISSUE THREAD

**Issue by captainjackrana** [rebrowser/rebrowser-patches#4]
Unable to patch puppeteer installation. 
Am I doing something wrong here?

```
npx rebrowser-patches patch
Config:
command = patch, packageName = puppeteer-core, patchName = fixRuntimeLeak
packagePath = /Users/MyLaptop/github/scraper/node_modules/puppeteer-core
patchFilePath = /Users/MyLaptop/.npm/_npx/faeaca83ff1ada18/node_modules/rebrowser-patches/patches/puppeteer-core/22.13.1/fixRuntimeLeak.patch
------
❌ FATAL ERROR: Internal error, patch command cannot find file to patch
```

**Comment by nwebson** [comment]
I just published an update, please run it like this:
```
REBROWSER_PATCHES_DEBUG=1 npx rebrowser-patches patch
```

This will give you more verbose output, so you could share it here, so I can get more insights. Thanks.

**Comment by captainjackrana** [comment]
How do you verify if this works?
I tried it on a different installation where the patch says it worked. 

However, [browserscan](https://www.browserscan.net/bot-detection) results did not change (CDP still was being detected)

**Comment by nwebson** [comment]
You need to enable it by settings env variable, for example `REBROWSER_PATCHES_RUNTIME_FIX_MODE=alwaysIsolated`.
Please read README file in the repo, it has all details about it.

**Comment by ottodriver** [comment]
@captainjackrana you need to "import" puppeteer, it doesn't work if you're using require.
Also, if you're using puppeteer-extra, you need to import puppeteer and patch it with "addExtra" after.

**Comment by captainjackrana** [comment]
This is the script I'm testing with
```

let puppeteer = require('puppeteer');

(async () => {
  const browser = await puppeteer.launch({

    headless: false,
   
  });
  const page = await browser.newPage();
  await page.goto('https://kaliiiiiiiiii.github.io/brotector/')
  //await page.goto('https://www.browserscan.net/bot-detection');
  await browser.close();
})()
```

Running it like this - 
`REBROWSER_PATCHES_RUNTIME_FIX_MODE=alwaysIsolated node index.js`


@ottodriver 
Can you share an example of using it with puppeteer-extra?

**Comment by ottodriver** [comment]
> This is the script I'm testing with
> 
> ```
> 
> let puppeteer = require('puppeteer');
> 
> (async () => {
>   const browser = await puppeteer.launch({
> 
>     headless: false,
>    
>   });
>   const page = await browser.newPage();
>   await page.goto('https://kaliiiiiiiiii.github.io/brotector/')
>   //await page.goto('https://www.browserscan.net/bot-detection');
>   await browser.close();
> })()
> ```
> 
> Running it like this - `REBROWSER_PATCHES_RUNTIME_FIX_MODE=alwaysIsolated node index.js`
> 
> Edit: Seems to be working after ottodriver's suggestion to use `import`
> 
> @ottodriver Can you share an example of using it with puppeteer-extra?

As I said it'll not work with require, you need to use import (type: 'module' in your package).
`
import { default as ppt } from 'puppeteer';
import { addExtra } from 'puppeteer-extra';
const puppeteer = addExtra(ppt);
`

**Comment by captainjackrana** [comment]
Thanks @ottodriver .. the detection seems to be clean now, combined with stealth plugin. Going to test this further, we can close this thread

**Comment by nwebson** [comment]
Thanks @ottodriver
