### ISSUE TITLE
PuppeteerSharp patch

### ISSUE THREAD

**Issue by IRusio** [rebrowser/rebrowser-patches#40]
Hey, do you know if there is an option to integrate your extension to puppetersharp library, written in .net? https://www.nuget.org/packages/PuppeteerSharp

**Comment by nwebson** [comment]
Please read how to patch it manually: https://github.com/rebrowser/rebrowser-patches?tab=readme-ov-file#how-to-patch-javapythonnet-versions-of-playwright
I'm not going to release a .NET package at this point. You just need to patch/replace the content of driver folder inside the PuppeteerSharp package.

**Comment by IRusio** [comment]
@nwebson unfortunatelly. there is no driver folder in those .net packages. Looks like they got rewritten in .net from the basics 😂, so I'm not surprised(.net/java love to do things "THATS THE PROPER WAY"). AS a simpler workaround i see an option to have a "remote" puppeteer/playwright, to whom I will just connect remotely(and it would be even easier to scale up a whole group of services, and have just a parent-child relationships. But i think in the long term an.net package with Rebrowser would be helpful :)

**Comment by nwebson** [comment]
@IRusio It does use nodejs driver under the hood: https://github.com/microsoft/playwright-dotnet/blob/main/src/tools/Playwright.Tooling/DriverDownloader.cs#L116

**Comment by IRusio** [comment]
that type of operation would require a complete package rebuild :/
