### ISSUE TITLE
playwright inspector is ruined with this patch

### ISSUE THREAD

**Issue by halvaenjoyer** [rebrowser/rebrowser-patches#41]
Repro: 
1) Install playwright@1.47.2
2) apply rebrowser-patch

Expected behavior:
`page.pause()` launches playwright inspector

Acrual result:
playwright inspector not attached properly
![playwright inspector not attached properly](https://github.com/user-attachments/assets/b4525a05-2722-4533-948e-76c094768f94)
As you can see recording is not possible and other features are not accessible

**Comment by igor2c** [comment]
I confirm this.

**Comment by nwebson** [comment]
I confirm this, too. It's quite tricky to investigate it, I will try to fix it once I have some time.
I think it shouldn't be a dealbreaker in prod env, and you can easily disable the fix during debugging.
