### ISSUE TITLE
iframe click not working

### ISSUE THREAD

**Issue by kbourro** [rebrowser/rebrowser-patches#43]
Example code of iframe click not working, already tested with puppeteer-core and it works. #accept-choices exist only with european ip, check with other element if you are out of europe.

        await page.goto(
          "https://www.w3schools.com/tags/tryit.asp?filename=tryhtml_iframe",
          { waitUntil: "domcontentloaded" }
        );
        await new Promise((resolve) => setTimeout(resolve, 3000));
        await (await page.$("#accept-choices")).click();
        let iframe = await (await page.$("#iframeResult")).contentFrame();
        console.log(iframe);
        iframe = await (
          await iframe.$(`iframe[src='https://www.w3schools.com']`)
        ).contentFrame();
        console.log(iframe);
        await (await iframe.$("#accept-choices")).click();

**Comment by BDawgBigMoney** [comment]
Im dealing with the same issue.

**Comment by nwebson** [comment]
Thanks for reporting this bug. I just fixed it and now `addBinding` method (default one) fully supports iframes.
Please check the new version and report back.
