### ISSUE TITLE
Running in docker /tmp/lighthouse.* files eats up all space

### ISSUE THREAD

**Issue by sfxter** [rebrowser/rebrowser-patches#45]
I noticed, that after some time my space is eaten up by docker container running rebrowser-puppeteer. 
After investigating, I found that inside container /tmp folder takes up 7Gb. Inside there were lighthouse.* files, probably created by chrome-launcher. 
Is there a way to disable creation of these files or remove them automatically?

**Comment by nwebson** [comment]
This issue is not related to the patches.
Try to check https://github.com/GoogleChrome/lighthouse/issues/15610
