### ISSUE TITLE
Scripts in Headless=False works, Headless=True blocked by Cloudflare...

### ISSUE THREAD

**Issue by espeka44** [rebrowser/rebrowser-patches#46]
First of all, note that without the rebrowser-patches, with the Playwright source library, there were problems passing Cloudflare detections; thanks for that.

I adjusted my webscraping task perfectly with Playwright corrected by rebrowser-patches lib without headless mode (headless=False). Now that I want to switch to headless mode (headless=True), the script is blocked by Cloudflare. I adjusted the header which has a difference in certain parameters such as "Headless" traces in the User-Agent or other elements, adjusted by comparison... despite all this Cloudflare blocks my script.

Any idea to bypass Cloudflare in headless=True ?

Playwright + Python

**Comment by kbourro** [comment]
Be aware that chrome 129 has a bug with headless true and set headless in user agent. That makes cloudflare detect it. Switch to 130.

**Comment by espeka44** [comment]
> Be aware that chrome 129 has a bug with headless true and it sets headless in user agent. That makes cloudflare detect it. Switch to 130.

I've already modified manually the "User-Agent" and "'Sec-Ch-Ua where "headless" traces were. Is not enought ?

I saw that Playwright 1.48.0 is out with the Chrome 130, but the Rebrowser-Playwright is not adjust on it. I will see how to install a specific version with the current version of Rebrowser.

**Comment by espeka44** [comment]
Don't work too with chromium 1140 (chrome v130) in headless mode, same issue :

For information : 
Default headers in the headless mode : 
 'user-agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) HeadlessChrome/130.0.6723.31 Safari/537.36',
'sec-ch-ua': '"Chromium";v="130", "HeadlessChrome";v="130", "Not?A_Brand";v="99"'

With headless=False :
'user-agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36',
'sec-ch-ua': '"Not?A_Brand";v="99", "Chromium";v="130"'

Obviously, i've manually modified headers to kick off "headless" word in all field...

**Comment by kbourro** [comment]
It detect it with other method, i don' t know exactly. To validate it just download chrome 130 on your pc and then set executable to use this one.

**Comment by espeka44** [comment]
Did it. Still stuck by Cloudflare.
`   chrome_path = Path(r'C:\Program Files\Google\Chrome\Application\chrome.exe')
    browser = pw.chromium.launch(headless=True,
                                 args=['--disable-blink-features=AutomationControlled'],
                                 executable_path=str(chrome_path)
                                 )
`

**Comment by espeka44** [comment]
Tested with the latest rebrowser-playwright (patch) for python (v1.4.8)... same result.

I'm always looking for where the differences are. Compared to cookies, in headless mode (=True), the "referrer_url" field does not exist; with headless=False, he is present inside.
My automated process performs an automatic login step. After submitting the form and being successful, the site is redirected to another page and this is this specific step that is captured by Cloudflare.

Any ideas ?

**Comment by espeka44** [comment]
I've solved my issue by using X Virtual Bufferframe (`sudo apt instal xvbf`).

I let `headless=False` in my script and launch it though XVBF with : `xvbf-run -a python main.py`
