### ISSUE TITLE
Support for BidiDriver

### ISSUE THREAD

**Issue by bestplay9384** [rebrowser/rebrowser-patches#47]
Hey, 

Are there any plans for providing support of freshly released almost full Firefox support via puppeteer? 

On my side it runs smoothly but with rebrowser patches webdriver availability is not being hidden, probably because of pathing CDP only?

**Comment by nwebson** [comment]
Hello, what service do you use to detect it? Could you share your code?

**Comment by bestplay9384** [comment]
Hey,

Info about WebDriver detection is from https://deviceandbrowserinfo.com/info_device.
About the code, to sum it up in any way - i have docker container based on node-slim (debian) with added aws-lambda-ric and aws-lambda-rie so it can be started in AWS Lambda Environment. In OS, firefox installed from official distribution (apt-get) then i just start nodejs with puppeteer script

```
...

const browser = await puppeteer.launch({
   executablePath: '/usr/bin/firefox',
   browser: 'firefox',
   protocol: 'webDriverBiDi',
   ...
});

...
```

Then i navigate to mentioned website and make screenshot. I also have some overriden methods in Puppeteer Page/Browser contexts this is why i saw it utilizes now their Bidi versions while running (`require('puppeteer-core/lib/cjs/puppeteer/bidi/Page.js').BidiPage`), this is why i think Your patches are omitted, they are only in `/cdp/` scope, not in `/bidi/` as far as i understand it correctly. 

Tell me what You think :) 
Thanks!

**Comment by nwebson** [comment]
These patches are designed for Chromium and CDP. Firefox, WebKit and BiDi are not supported (at least yet).
Thanks for reporting though.
