### ISSUE TITLE
Question about proper versioning

### ISSUE THREAD

**Issue by aumeshm** [rebrowser/rebrowser-patches#53]
Im a bit confused on the best version to use.
 
The readme suggests using `23.3.1` for both rebrowser-puppeteer and rebrowser-puppeteer-core. However for `rebrowser-puppeteer-core`, I noticed that the default branch is `23.6.1`. Which version, do the latest patches (especially the one on iframes) apply to?

**Comment by nwebson** [comment]
Always use the latest version. Readme has just an example. Current version is 23.6.101 - https://www.npmjs.com/package/rebrowser-puppeteer-core?activeTab=versions
