### ISSUE TITLE
ModuleNotFoundError: No module named 'rebrowser_playwright._repo_version'

### ISSUE THREAD

**Issue by 2516455367** [rebrowser/rebrowser-patches#55]
ModuleNotFoundError: No module named 'rebrowser_playwright._repo_version'

**Comment by nwebson** [comment]
Thanks for the report. Seems like there was some issue. I made a new version `1.48.100` and uploaded it to pypi: https://pypi.org/project/rebrowser-playwright/
Please update it and let me know if it's still broken.
