### ISSUE TITLE
Cannot get world, error: TypeError: Cannot set properties of undefined (setting 'main')

### ISSUE THREAD

**Issue by brutaldev** [rebrowser/rebrowser-patches#57]
Testing out "addBinding" with Playwright and using some complex initialization scripts with timers and the log gets flooded with several of these errors:
```
[rebrowser-patches][frames._context] cannot get world, error: TypeError: Cannot set properties of undefined (setting 'main')
    at \.playwright\package\lib\server\frames.js:715:38
    at runNextTicks (node:internal/process/task_queues:60:5)
    at process.processImmediate (node:internal/timers:454:9)
    at async Frame.evaluateExpression (\.playwright\package\lib\server\frames.js:769:21)
```
The scripts still work though so not sure if this error is serious or can be treated as a warning?

**Comment by nwebson** [comment]
Just released a new version, this issue should be fixed there.
https://github.com/rebrowser/rebrowser-patches/releases/tag/1.0.16
