### ISSUE TITLE
Getting past useragent rebrowser-bot-detection test

### ISSUE THREAD

**Issue by aumeshm** [rebrowser/rebrowser-patches#63]
Is there anyway besides using chrome to get past the useragent test? I looked at the source code and tried to define properties, but then I fail the navigator detection test.

Alternatively, I tried using chrome but have to do it within docker. Puppeteer-Real-Browser has been running into port connection issues when setting up Docker and Chrome, so I tried finding alternative solutions. Any suggestions here will help out a lot. Thanks!

**Comment by aumeshm** [comment]
I actually found this really useful to define navigator properties without triggering the detection test: https://github.com/berstend/puppeteer-extra/issues/207#issuecomment-635286816

**Comment by nwebson** [comment]
Do you mean `navigatorWebdriver` test in rebrowser-bot-detector? It's quite basic, the real tests used by antidetect scripts are much deeper, they can detect most of these spoofs that were actual 2-3 years ago. So, if you pass the test on bot-detector page, it doesn't mean that it will work for DataDome and other services. The real way to fix it is to build your own version of Chromium, or just use some real browser such as a remote browser (see [rebrowser.net](https://rebrowser.net)).
I'm closing this issue as it's not relevant to the patches itself.

**Comment by nwebson** [comment]
There are many places such as reddit and discord channels where you can ask some people for an advice.
