### ISSUE TITLE
Playwright patches do not pass bot-detector test

### ISSUE THREAD

**Issue by SazCoR** [rebrowser/rebrowser-patches#66]
I have applied the rebrowser patches to Playwright for Python both manually and by installing the package. However, the bot-detection test at https://bot-detector.rebrowser.net/ does not pass, despite following the instructions provided in your repository.

Here is the generic Python code I used to test the detection:

from playwright.sync_api import sync_playwright

def test_bot_detection():
        with sync_playwright() as p:
        browser = p.chromium.launch_persistent_context(
            headless=False)
        page = browser.new_page()
        page.goto("https://bot-detector.rebrowser.net/")
        input("Press Enter to close...")
        browser.close()

if __name__ == "__main__":
    test_bot_detection()

Even after applying the patches and running the above code, the test still flags several issues (e.g., navigator.webdriver, runtime.enable leak, etc.). Could you please confirm if there is an additional step or configuration required to pass the bot-detection test? It just does not bypass anything, I don't know If I am doing something wrong.

Thank you for your assistance!

![image](https://github.com/user-attachments/assets/8c796c3d-6c56-4514-a084-feabae1d5c35)

**Comment by nwebson** [comment]
Webdriver leak should be fixed by using a switch in Chrome, it says it on the page.

For the patches, how did you apply it manually? In your code you're using the original package. Have you tried https://pypi.org/project/rebrowser-playwright/ ?

**Comment by vxphuongictu** [comment]
![image](https://github.com/user-attachments/assets/183274b8-8e6c-4b9f-9cb9-84b0c55085ba)
![image](https://github.com/user-attachments/assets/75e2a003-97a0-4f70-bd6b-abbcb1b97fa4)
I was also discovered to be a robot

**Comment by SazCoR** [comment]
It works now, by connecting over cdp to an existing chrome session (launching chrome.exe with --remote-debugging-port=9222) , using the rebrowser_playwight python package and setting the viewport to my screen, it passes all the tests, thank you so much!

![image](https://github.com/user-attachments/assets/19ac79e0-6b79-43b5-aeb0-ccb5ba38a0ad)

**Comment by SazCoR** [comment]
![image](https://github.com/user-attachments/assets/85b9d7a7-d804-405b-bc3b-c409ac7225ee)
I am not getting detected using CDP, I don't really know why, I am looking for another way of doing it tho

**Comment by vxphuongictu** [comment]
> @vxphuongictu your python package is not patched, that's why you see this CDP detection @SazCoR thanks for the feedback

I ran pip install rebrowser-playwright and followed the instructions. Where did I go wrong?

**Comment by vxphuongictu** [comment]
![image](https://github.com/user-attachments/assets/ef93e0ec-916b-45e9-94d8-95985c2e8218)
After updating the code like this, everything worked fine. Thank you for your quick help ^^
