### ISSUE TITLE
Doesn't support playwright 1.49

### ISSUE THREAD

**Issue by D4Vinci** [rebrowser/rebrowser-patches#68]
Hey, Playwright Python has a new version that introduces a lot of good stuff.
Please update the code:
https://github.com/microsoft/playwright/issues/33566

Also, consider finding a way to dynamically patch the next playwright versions instead of having to update the code with every new version.

**Comment by nwebson** [comment]
Just released a new version, this issue should be fixed there.
https://github.com/rebrowser/rebrowser-patches/releases/tag/1.0.16
