### ISSUE TITLE
[rebrowser-playwright] Tries to import uninstalled modules and fails to parse a module

### ISSUE THREAD

**Issue by gohoski** [rebrowser/rebrowser-patches#72]
When trying to import any browser from `rebrowser-playwright` or `rebrowser-playwright-core`, there is an error while trying to import `electron`, `bufferutil`, `utf-8-validate` and `chromium-bidi`. These packages are not installed automatically at all and need to be manually installed

However, when these modules are manually installed, there is another error about a module parse :
```typescript
 ○ Compiling /api/custom_generate ...
 ⨯ ./node_modules/rebrowser-playwright-core/lib/vite/recorder/assets/codicon-DCmgc-ay.ttf
Module parse failed: Unexpected character '' (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders 
(Source code omitted for this binary file)

Import trace for requested module:
./node_modules/rebrowser-playwright-core/lib/vite/recorder/assets/codicon-DCmgc-ay.ttf
./node_modules/rebrowser-playwright-core/lib/vite/recorder/ sync ^\.\/.*$
./node_modules/rebrowser-playwright-core/lib/server/recorder/recorderApp.js
./node_modules/rebrowser-playwright-core/lib/server/debugController.js
./node_modules/rebrowser-playwright-core/lib/server/playwright.js
./node_modules/rebrowser-playwright-core/lib/browserServerImpl.js
./node_modules/rebrowser-playwright-core/lib/inProcessFactory.js
./node_modules/rebrowser-playwright-core/lib/inprocess.js
./node_modules/rebrowser-playwright-core/index.js
./node_modules/rebrowser-playwright-core/index.mjs
./src/lib/SunoApi.ts
./src/app/api/custom_generate/route.ts
```
(We are using Next.js.)

I had tried importing it using `import * as playwright from 'rebrowser-playwright(-core)'`, `import { firefox }` and others, and still the same error .

This error does not happen with original Playwright. Please help ASAP as we need to solve this fast.

**Comment by gohoski** [comment]
This error happens even if I install playwright-core separately and use the `npx rebrowser-patches@latest patch` command.

**Comment by nwebson** [comment]
It's hard to tell what could be wrong here as there are too many different pieces. Try to provide some minimal code example.

**Comment by gohoski** [comment]
omg it was an issue on my end. Sorry for bothering you. However, for others that are looking for the solution on Next.js + Webpack, add this to your next.config:
```mjs
/** @type {import('next').NextConfig} */
const nextConfig = {
  webpack: (config) => {
    config.module.rules.push({
      test: /\.(ttf|html)$/i,
      type: 'asset/resource'
    });

    return config;
  },
};  

export default nextConfig;
```
